"""add order status history and notification fields

Revision ID: 1b6c96e824c8
Revises: 20240101000000
Create Date: 2026-09-03 13:58:01.887528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b6c96e824c8'
down_revision = '20240101000000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_expires', ['expires_at'], unique=False)
        batch_op.create_index('ix_notification_user_type', ['user_id', 'type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notification_user_type')
        batch_op.drop_index('ix_notification_expires')

    # ### end Alembic commands ###
