"""upgrade subscription system

Revision ID: 8b338649831e
Revises: 1b6c96e824c8
Create Date: 2026-09-03 16:30:46.044854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b338649831e'
down_revision = '1b6c96e824c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmation_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('renewal_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('renewal_count')
        batch_op.drop_column('duration_days')
        batch_op.drop_column('confirmation_expiry')
        batch_op.drop_column('confirmation_attempts')

    # ### end Alembic commands ###
