"""Add Reels models

Revision ID: cee1313e1a42
Revises: 8b338649831e
Create Date: 2026-09-03 22:33:00.971416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee1313e1a42'
down_revision = '8b338649831e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(length=300), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=300), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.create_index('ix_reel_active_created', ['is_active', 'created_at'], unique=False)
        batch_op.create_index('ix_reel_store_created', ['store_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reels_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reels_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_reels_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reels_store_id'), ['store_id'], unique=False)

    op.create_table('reel_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reel_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_comments_reel_id'), ['reel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reel_comments_user_id'), ['user_id'], unique=False)

    op.create_table('reel_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("reaction_type IN ('like', 'love', 'wow', 'sad', 'angry')", name='ck_reel_reaction_type_valid'),
    sa.ForeignKeyConstraint(['reel_id'], ['reels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reel_id', 'user_id', name='uq_reel_user_reaction')
    )
    with op.batch_alter_table('reel_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_reactions_reel_id'), ['reel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reel_reactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reel_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_reel_reactions_reel_id'))

    op.drop_table('reel_reactions')
    with op.batch_alter_table('reel_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_reel_comments_reel_id'))

    op.drop_table('reel_comments')
    with op.batch_alter_table('reels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reels_store_id'))
        batch_op.drop_index(batch_op.f('ix_reels_product_id'))
        batch_op.drop_index(batch_op.f('ix_reels_is_active'))
        batch_op.drop_index(batch_op.f('ix_reels_created_at'))
        batch_op.drop_index('ix_reel_store_created')
        batch_op.drop_index('ix_reel_active_created')

    op.drop_table('reels')
    # ### end Alembic commands ###
